# You can get more information regarding the YAML file here:
# https://docs.codemagic.io/getting-started/yaml/

# Workflow setup for building Native Android project
workflows:
    # The following workflow is for generating a debug build
    debug-workflow: # workflow ID
      name: Native Android # workflow name
      max_build_duration: 60 # max build duration in minutes
      scripts:
        - |
          # launching android emulator
          emulator -avd emulator > /dev/null 2>&1 &
        - |
          # set up debug keystore
          rm -f ~/.android/debug.keystore
          keytool -genkeypair \
            -alias androiddebugkey \
            -keypass android \
            -keystore ~/.android/debug.keystore \
            -storepass android \
            -dname 'CN=Android Debug,O=Android,C=US' \
            -keyalg 'RSA' \
            -keysize 2048 \
            -validity 10000
        - |
          # run tests
          ./gradlew test
          ./gradlew connectedAndroidTest
        - |  
          # build debug apk
          ./gradlew assembleDebug
      artifacts:
        - app/build/**/outputs/**/*.apk
      publishing:
        email:
          recipients:
            - luismiguel.hernandez@ulpgc.es # enter your email id here
